const mockData = [
    {
        id: '1',
        title: 'Kill Bill: Vol 2',
        date: '2004-04-08',
        year: 2004,
        genre: 'Crime',
        img: 'https://www.kinopoisk.ru/im/poster/2/1/2/kinopoisk.ru-Kill-Bill_3A-Vol-2-2126602--o--.jpg',
        raiting: 4.5,
        duration: 136,
        description: 'Kill Bill: Volume 2 is a 2004 American martial arts film written and directed by Quentin Tarantino. It stars Uma Thurman as the Bride, who continues her campaign of revenge against the Deadly Viper Assassination Squad (Lucy Liu, Michael Madsen, Daryl Hannah, and Vivica A. Fox) and their leader Bill (David Carradine), who tried to kill her and her unborn child.',
        url: 'http://test.test',
    },
    {
        id: '2',
        title: 'From Dusk till Dawn',
        date: '1996-01-17',
        year: 1996,
        genre: 'Horror',
        img:'https://upload.wikimedia.org/wikipedia/en/f/f0/From_dusk_till_dawn_poster.jpg',
        raiting: 4.5,
        duration: 108,
        description: 'From Dusk till Dawn is a 1996 American action horror film directed by Robert Rodriguez and written by Quentin Tarantino.[4] It stars Harvey Keitel, George Clooney, Tarantino, and Juliette Lewis. After enjoying financial success at the box office, it has since become a cult film.',
        url: 'http://test.test',
    },
    {
        id: '3',
        title: 'The Dark Knight',
        date: '2008-06-14',
        year: 2008,
        genre: 'Crime',
        img: 'https://upload.wikimedia.org/wikipedia/en/8/8a/Dark_Knight.jpg',
        raiting: 4.5,
        duration: 152,
        description: 'The Dark Knight is a 2008 superhero film directed, produced, and co-written by Christopher Nolan. Based on the DC Comics character Batman, the film is the second installment of Nolan\'s The Dark Knight Trilogy and a sequel to 2005\'s Batman Begins, starring Christian Bale and supported by Michael Caine, Heath Ledger, Gary Oldman, Aaron Eckhart, Maggie Gyllenhaal, and Morgan Freeman. In the film, Bruce Wayne / Batman (Bale), Police Lieutenant James Gordon (Oldman) and District Attorney Harvey Dent (Eckhart) form an alliance to dismantle organized crime in Gotham City, but are menaced by an anarchistic mastermind known as the Joker (Ledger), who seeks to undermine Batman\'s influence and throw the city into anarchy.',
        url: 'http://test.test',
    },
    {
        id: '4',
        title: 'Unknown',
        date: '2010-11-13',
        year: 2010,
        genre: 'Documentary',
        raiting: 4.0,
        duration: 90,
        description: 'Test Unknown MOVIE',
        url: 'http://test.test',
    },
    {
        id: '5',
        title: 'Ace Ventura: When Nature Calls',
        date: '1995-11-10',
        year: 1995,
        genre: 'Comedy',
        img:'https://upload.wikimedia.org/wikipedia/en/b/b9/AceVenturaWhenNatureCallsposter.jpg',
        raiting: 5.0,
        duration: 94,
        description: 'Ace Ventura: When Nature Calls (also known as Ace Ventura 2: When Nature Calls) is a 1995 American detective comedy film and the sequel to Ace Ventura: Pet Detective (1994). Jim Carrey reprises his role as the title character Ace Ventura, a detective who specializes in retrieval of tame and captive animals. Ian McNeice, Simon Callow, and Sophie Okonedo co-star. Tommy Davidson, who co-starred with Carrey on the show In Living Color, makes a cameo appearance in the film.',
        url: 'http://test.test',
    },
    {
        id: '6',
        title: 'High Crimes',
        date: '2002-04-05',
        year: 2002,
        genre: 'Crime',
        img: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/High_Crimes_poster.JPG/220px-High_Crimes_poster.JPG',
        raiting: 4.4,
        duration: 115,
        description: 'High Crimes is a 2002 American legal thriller film directed by Carl Franklin and starring Ashley Judd and Morgan Freeman, reunited from the 1997 film Kiss the Girls. The screenplay by Yuri Zeltser and Grace Cary Bickley is based on Joseph Finder\'s 1998 novel of the same name.',
        url: 'http://test.test',
    }
];

export default mockData;